# Generated by Django 3.1.5 on 2021-07-05 08:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Service', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=20)),
                ('Company', models.CharField(max_length=100, null=True)),
                ('Message', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Link', models.CharField(max_length=200)),
                ('Customer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Querie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
                ('Question', models.TextField()),
                ('slug2', models.SlugField(blank=True, null=True, unique=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Meta_Tags', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Category', models.CharField(max_length=50)),
                ('Body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Views', models.IntegerField(default=0, null=True)),
                ('Likes', models.IntegerField(default=0, null=True)),
                ('Dis_Likes', models.IntegerField(default=0, null=True)),
                ('CommentsCounts', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Body', models.TextField(null=True)),
                ('Time', models.DateTimeField(auto_now_add=True, null=True)),
                ('Post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.post')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reply', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.querie')),
                ('user', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
