# Generated by Django 2.2.14 on 2021-08-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_auto_20210815_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientID', models.CharField(max_length=30)),
                ('Clinic', models.CharField(max_length=300)),
                ('Prescriber', models.CharField(max_length=200)),
                ('Invoice', models.CharField(max_length=20)),
                ('BalanceToPay', models.CharField(max_length=30)),
                ('Surgery', models.CharField(max_length=100)),
                ('Fee', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=100)),
                ('Note', models.TextField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
