# Generated by Django 2.2.14 on 2021-08-30 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_auto_20210830_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='BalanceToPay',
            new_name='Balance_To_Pay',
        ),
    ]
