# Generated by Django 2.2.14 on 2021-09-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_patient_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='OralScan',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='TreatmentRequest',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
