# Generated by Django 2.2.14 on 2021-09-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_auto_20210905_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='Image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='Image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
