# Generated by Django 2.2.14 on 2021-09-05 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolioApp', '0008_auto_20210905_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Proposed_Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField(null=True)),
                ('Time', models.DateTimeField(auto_now_add=True, null=True)),
                ('ProposedTreatment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
