# Generated by Django 2.2.14 on 2021-09-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0012_auto_20210905_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Status',
            field=models.CharField(default='Pending', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TreatmentRequestStatus',
        ),
    ]
