# Generated by Django 2.2.14 on 2021-09-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0013_auto_20210905_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Image1',
            field=models.ImageField(default='images/Logo2.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Image2',
            field=models.ImageField(default='images/Logo2.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Image3',
            field=models.ImageField(default='images/Logo2.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='OralScan',
            field=models.FileField(default='images/Logo2.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentRequest',
            field=models.FileField(default='images/Logo2.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='ProposedTreatment',
            field=models.FileField(default='images/Logo2.png', upload_to=''),
        ),
    ]
