# Generated by Django 2.2.14 on 2021-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0014_auto_20210905_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Balance_To_Pay',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Fee',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='PatientID',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Prescriber',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Surgery',
        ),
        migrations.AlterField(
            model_name='patient',
            name='Image1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Image2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Image3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='OralScan',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='TreatmentRequest',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='ProposedTreatment',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
