# Generated by Django 2.2.14 on 2021-09-06 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0015_auto_20210906_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientproposedtreatment',
            old_name='Note',
            new_name='Invoice',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Invoice',
        ),
    ]
