# Generated by Django 2.2.14 on 2021-09-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0017_dentistprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DentistProfile',
        ),
    ]
