# Generated by Django 2.2.14 on 2021-09-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0020_auto_20210909_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Review', 'Review'), ('Decline', 'Decline')], default='Pending', max_length=20, null=True),
        ),
    ]
