# Generated by Django 2.2.14 on 2021-09-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0022_dentistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientproposedtreatment',
            name='Note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='patientproposedtreatment',
            name='Invoice',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
