# Generated by Django 2.2.14 on 2021-09-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0023_auto_20210909_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='OralScan',
            new_name='OralScanLower',
        ),
        migrations.AddField(
            model_name='patient',
            name='OralScanUpper',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='patient',
            name='ThreeDViewRequest',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
