# Generated by Django 2.2.14 on 2021-09-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0024_auto_20210909_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ThreeDViewRequest',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
