# Generated by Django 2.2.14 on 2021-09-09 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0025_auto_20210909_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientproposedtreatment',
            name='ThreeDViewProposed',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
