# Generated by Django 2.2.14 on 2021-09-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0027_patient_internalstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentistprofile',
            old_name='Address',
            new_name='Address1',
        ),
        migrations.AddField(
            model_name='dentistprofile',
            name='Address2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentistprofile',
            name='City',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentistprofile',
            name='Country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dentistprofile',
            name='Postcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
