# Generated by Django 2.2.14 on 2021-09-13 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolioApp', '0028_auto_20210909_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=50)),
                ('PatientPhone', models.CharField(max_length=20)),
                ('PatientEmail', models.CharField(max_length=40)),
                ('ReferralReason', models.CharField(choices=[('Consultation', 'Consultation'), ('Implant', 'Implant'), ('Orthodontics', 'Orthodontics'), ('Root Canal Treatment', 'Root Canal Treatment'), ('Implant', 'Crown and Veneers'), ('Retainer', 'Retainer')], default='Consultation', max_length=60, null=True)),
                ('Status', models.CharField(choices=[('Declined', 'Declined'), ('TC', 'TC')], default='In Progress', max_length=40, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
