# Generated by Django 2.2.14 on 2021-09-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0029_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='ThreeDViewRequest',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
