# Generated by Django 2.2.14 on 2021-09-14 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0030_auto_20210914_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ArrangeCollection',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
