# Generated by Django 2.2.14 on 2021-09-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0031_patient_arrangecollection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Note',
            new_name='DentistNote',
        ),
        migrations.AddField(
            model_name='patient',
            name='AdminNote',
            field=models.TextField(default='No Note Added'),
        ),
    ]
