# Generated by Django 2.2.14 on 2021-09-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0034_auto_20210914_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRequestFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
