# Generated by Django 2.2.14 on 2021-09-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0035_treatmentrequestfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='Status',
            field=models.CharField(choices=[('Inprogress', 'Inprogress'), ('Accepted', 'Accepted'), ('TC', 'TC'), ('Declined', 'Declined')], default='In Progress', max_length=40, null=True),
        ),
    ]
