# Generated by Django 2.2.14 on 2021-09-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0036_auto_20210916_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='PatientSurname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='ReferralReason',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Implant', 'Implant'), ('Orthodontics', 'Orthodontics'), ('Root Canal Treatment', 'Root Canal Treatment'), ('Implant', 'Crown and Veneers')], default='Consultation', max_length=60, null=True),
        ),
    ]
