# Generated by Django 2.2.14 on 2021-09-25 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0039_auto_20210925_0302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dentistprofile',
            old_name='Address',
            new_name='Phone',
        ),
    ]
